################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Docker Compose File
#
# This Docker File intend to Create a Complete Dev Environment
# for Splash Sellsy Connector
#
# Services are Split in ./docker/*.yml files
#
# For a faster access to you container, you can add this IP to /etc/hosts
#
#    172.118.0.100       toolkit.sellsy.local
#    172.118.0.200       sandbox.sellsy.local
#
################################################################################

name: "splash-sellsy"

include:
    ################################################################################
    # Splash Toolkit Container
    - ./docker/toolkit.yml
    ################################################################################
    # Sellsy Api SandBox
    - ./docker/sandbox.yml
    ################################################################################
    # Php Sdk Container, where Composer, GrumPHP & PhpUnit are executed
    - ./docker/php.yml
    ################################################################################
    # Public Https Tunnel, for Sellsy WebHooks callbacks
    - ./docker/ngrok.yml

networks:
    ################################################################################
    # Default Private Network
    sellsy:
        driver: bridge
        ipam:
            config:
                - subnet: 172.118.0.0/24
    ################################################################################
    # External Splash Network
    splashsync:
        external: true
