services:
    _defaults:
        autowire:       true
        autoconfigure:  true

    ################################################################################
    # SPLASH Sellsy Connector Service
    splash.connectors.sellsy:
        class:      Splash\Connectors\Sellsy\Connector\SellsyConnector
        shared:     false
        calls:
          - setMetaDir: ["%kernel.cache_dir%"]
        tags:
          - { name: "splash.connector" }

    ################################################################################
    # Auto-wiring for Actions
    Splash\Connectors\Sellsy\Actions\:
        resource:   '../../Actions'
        tags:
          - { name: 'controller.service_arguments' }

    ################################################################################
    # Auto-wiring for Services
    Splash\Connectors\Sellsy\Services\:
        resource:   '../../Services'

    ################################################################################
    Splash\OpenApi\Visitor\AbstractVisitor:
        class:  Splash\OpenApi\Visitor\AbstractVisitor